local _, RHP = ...
RHP.Localisation = setmetatable({ }, {__index=function (t,k) return k end})
local L = RHP.Localisation
local locale = GetLocale()

----------------------------------------------------------------------------------------------------------------------
-- enUS / enGB / Default
----------------------------------------------------------------------------------------------------------------------
L = L or {}
L["ADDON_NAME"] = "Random Hearthstone Plus"
L["NO_VALID_CHOSEN"] = "|cff42E400Random Hearthstone Plus|r - No valid toy chosen. Setting macro to use Hearthstone"
L["MACRO_NAME"] = "Random Hearth"
L["RENOWN_LOCKED"] = "Renown locked"
L["THANKS"] = "Thanks for using my addon"
L["DESCRIPTION"] = "Add or remove hearthstone and teleport toys from rotation"
L["SELECT_ALL"] = "Select all"
L["DESELECT_ALL"] = "Deselect all"
L["OPT_MACRO_ICON"] = "Macro icon"
L["COV_ONLY"] = "Allow player's current Covenant hearthstone only"
L["DAL_R_CLICK"] = "Cast Dalaran Hearth on macro right click"
L["GAR_M_CLICK"] = "Cast Garrison Hearth on macro middle click"
L["SETUP_1"] = "Setting up Random Hearthstone Plus database."
L["SETUP_2"] = "You can now cast Dalaran hearth with right click, and Garrison hearth with middle mouse button."
L["SETUP_3"] = "These settings can be changed in the options, type /rhp"
L["RANDOM"] = "Random"
L["HEARTHSTONE"] = "Hearthstone"
L["MACRO_NOT_FOUND"] = "|cff42E400Random Hearthstone Plus|r - Macro not found, creating macro named '"
L["UPDATE_MACRO_NAME"] = "|cff42E400Random Hearthstone Plus|r - Updating macro name to '"
L["UNIQUE_NAME_ERROR"] = "Macro name in use!\nPlease pick a unique name."
L["OPT_MACRO_NAME"] = "Macro name"
L["LOGIN_MESSAGE_1"] = "|cff42E400Random Hearthstone Plus|r - Now supports Shift/Ctrl/Alt modifier key bindings."
L["LOGIN_MESSAGE_2"] = "Type /rhp to open options."
L["MOD_BINDINGS"] = "Modifier Key Bindings"
L["MOD_SHIFT"] = "Shift"
L["MOD_CTRL"] = "Ctrl"
L["MOD_ALT"] = "Alt"
L["MOD_LEFT_CLICK"] = "Left Click"
L["MOD_RIGHT_CLICK"] = "Right Click"
L["MOD_MIDDLE_CLICK"] = "Middle Click"
L["DALARAN_HEARTH"] = "Dalaran Hearthstone"
L["GARRISON_HEARTH"] = "Garrison Hearthstone"
L["CUSTOM_SPELL"] = "Custom Spell..."
L["CUSTOM_ITEM"] = "Custom Item..."
L["CUSTOM_MACRO"] = "Custom Macro..."
L["CUSTOM_SPELL_PROMPT"] = "Enter spell name:"
L["CUSTOM_ITEM_PROMPT"] = "Enter item name or ID:"
L["CUSTOM_MACRO_PROMPT"] = "Enter macro name:"
L["DEFAULT_RESTORED"] = "Default settings restored."
L["TOGGLE_ON"] = "On"
L["TOGGLE_OFF"] = "Off"
L["TELEPORT_TOYS"] = "Teleport Toys"
L["HEARTHSTONE_TOYS"] = "Hearthstone Toys"

----------------------------------------------------------------------------------------------------------------------
-- zhCN
----------------------------------------------------------------------------------------------------------------------
if locale == "zhCN" then
    L = L or {}
    L["ADDON_NAME"] = "随机炉石增强版"
    L["NO_VALID_CHOSEN"] = "|cff42E400随机炉石增强版|r - 没有选择有效的炉石玩具。设置宏来使用炉石"
    L["MACRO_NAME"] = "随机炉石"
    L["RENOWN_LOCKED"] = "盟约锁定"
    L["THANKS"] = "感谢使用我的插件"
    L["DESCRIPTION"] = "添加或移除炉石和传送玩具的随机轮换"
    L["SELECT_ALL"] = "全部启用"
    L["DESELECT_ALL"] = "全部禁用"
    L["OPT_MACRO_ICON"] = "宏图标"
    L["COV_ONLY"] = "仅允许玩家当前盟约的炉石"
    L["DAL_R_CLICK"] = "鼠标右键点击宏使用达拉然炉石"
    L["GAR_M_CLICK"] = "鼠标中键点击宏使用要塞炉石"
    L["SETUP_1"] = "正在设置随机炉石增强版数据库。"
    L["SETUP_2"] = "现在您可以鼠标右键使用达拉然炉石，鼠标中键使用要塞炉石。"
    L["SETUP_3"] = "这些设置可以在选项中更改，输入 /rhp"
    L["RANDOM"] = "随机"
    L["HEARTHSTONE"] = "炉石"
    L["MACRO_NOT_FOUND"] = "|cff42E400随机炉石增强版|r - 未找到宏，正在创建宏名为 '"
    L["UPDATE_MACRO_NAME"] = "|cff42E400随机炉石增强版|r - 更新宏名为 '"
    L["UNIQUE_NAME_ERROR"] = "宏名称已被使用！\n请选择一个唯一的名称。"
    L["OPT_MACRO_NAME"] = "宏名称"
    L["LOGIN_MESSAGE_1"] = "|cff42E400随机炉石增强版|r - 现支持 Shift/Ctrl/Alt 修饰键绑定。"
    L["LOGIN_MESSAGE_2"] = "输入 /rhp 打开设置。"
    L["MOD_BINDINGS"] = "修饰键绑定"
    L["MOD_SHIFT"] = "Shift"
    L["MOD_CTRL"] = "Ctrl"
    L["MOD_ALT"] = "Alt"
    L["MOD_LEFT_CLICK"] = "左键"
    L["MOD_RIGHT_CLICK"] = "右键"
    L["MOD_MIDDLE_CLICK"] = "中键"
    L["DALARAN_HEARTH"] = "达拉然炉石"
    L["GARRISON_HEARTH"] = "要塞炉石"
    L["CUSTOM_SPELL"] = "自定义法术..."
    L["CUSTOM_ITEM"] = "自定义物品..."
    L["CUSTOM_MACRO"] = "自定义宏..."
    L["CUSTOM_SPELL_PROMPT"] = "输入法术名称："
    L["CUSTOM_ITEM_PROMPT"] = "输入物品名称或ID："
    L["CUSTOM_MACRO_PROMPT"] = "输入宏名称："
    L["DEFAULT_RESTORED"] = "已恢复默认设置。"
    L["TOGGLE_ON"] = "开"
    L["TOGGLE_OFF"] = "关"
    L["TELEPORT_TOYS"] = "传送玩具"
    L["HEARTHSTONE_TOYS"] = "炉石玩具"
end
